import { Box, Divider, InputAdornment, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { Inventory2, ReceiptLong, Search } from '@mui/icons-material';
import SectionPaper from '../components/common/SectionPaper';
import EmptyState from '../components/common/EmptyState';
import OrderRow from '../components/orders/OrderRow';
import { orderStatuses, statusLabels } from '../constants/orders';
import { formatDate, formatMoney } from '../utils/formatters';

function OrderDetails({ order, onStatusChange }) { if (!order) return <SectionPaper><EmptyState icon={<ReceiptLong fontSize="large" />} title="Выберите заказ" /></SectionPaper>; return <SectionPaper sx={{ p: { xs: 2, sm: 2.5 } }}><Stack spacing={2.25}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography variant="h6">Заказ #{order.id}</Typography><Typography variant="body2" color="text.secondary">{formatDate(order.created_at)}</Typography></Box><TextField select label="Статус" size="small" value={order.status} onChange={(event) => onStatusChange(order.id, event.target.value)} sx={{ minWidth: 190 }}>{orderStatuses.map((status) => <MenuItem key={status} value={status}>{statusLabels[status]}</MenuItem>)}</TextField></Stack><Box sx={{ display: 'grid', gap: 1.25, gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' } }}><TextField label="Покупатель" size="small" value={order.customer_name || ''} InputProps={{ readOnly: true }} /><TextField label="Телефон" size="small" value={order.customer_phone || ''} InputProps={{ readOnly: true }} /><TextField label="Адрес доставки" size="small" value={order.delivery_address || ''} InputProps={{ readOnly: true }} sx={{ gridColumn: { sm: '1 / -1' } }} /></Box><Divider /><Stack spacing={1.25}>{(order.items || []).map((item) => <Box key={item.id} sx={{ display: 'grid', gridTemplateColumns: '64px minmax(0, 1fr) auto', gap: 1.5, p: 1.25, border: '1px solid', borderColor: 'divider', borderRadius: 2, alignItems: 'center' }}><Box sx={{ width: 64, height: 64, display: 'grid', placeItems: 'center', borderRadius: 1.5, bgcolor: 'action.hover', overflow: 'hidden' }}>{item.image ? <Box component="img" src={item.image} alt={item.name} sx={{ width: '100%', height: '100%', objectFit: 'contain' }} /> : <Inventory2 color="disabled" />}</Box><Box sx={{ minWidth: 0 }}><Typography fontWeight={800}>{item.brand} {item.article}</Typography><Typography variant="body2" color="text.secondary">{item.name}</Typography><Typography variant="caption" color="text.secondary">{item.supplier} · Артикул: {item.supplier_article || 'не указан'}</Typography></Box><Box textAlign="right"><Typography fontWeight={800}>{formatMoney(item.total)}</Typography><Typography variant="caption" color="text.secondary">{item.quantity} × {formatMoney(item.price)}</Typography></Box></Box>)}</Stack><Stack direction="row" justifyContent="space-between"><Typography variant="h6">Итого</Typography><Typography variant="h6" color="primary">{formatMoney(order.total_amount)}</Typography></Stack></Stack></SectionPaper> }

export default function OrdersPage({ orders, selectedOrder, setSelectedOrder, filters, setFilters, onStatusChange }) { return <Stack spacing={3}><Box><Typography variant="h5">Заказы</Typography><Typography color="text.secondary">Поиск, статусы и состав заказов</Typography></Box><Box sx={{ display: 'grid', gap: 2, gridTemplateColumns: { xs: '1fr', lg: '400px minmax(0, 1fr)' }, alignItems: 'start' }}><SectionPaper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2, display: 'grid', gap: 1.25 }}><TextField size="small" placeholder="Номер, телефон, артикул" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} InputProps={{ startAdornment: <InputAdornment position="start"><Search /></InputAdornment> }} /><TextField select size="small" label="Статус" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><MenuItem value="">Все статусы</MenuItem>{orderStatuses.map((status) => <MenuItem key={status} value={status}>{statusLabels[status]}</MenuItem>)}</TextField></Box><Divider />{orders.length ? <Stack divider={<Divider />}>{orders.map((order) => <OrderRow key={order.id} order={order} onClick={() => setSelectedOrder(order)} />)}</Stack> : <EmptyState icon={<ReceiptLong fontSize="large" />} title="Заказы не найдены" />}</SectionPaper><OrderDetails order={selectedOrder || orders[0]} onStatusChange={onStatusChange} /></Box></Stack>; }
