import { Box, Card, CardContent, Divider, InputAdornment, Stack, TextField, Typography } from '@mui/material';
import { Paid, People, ReceiptLong, Search } from '@mui/icons-material';
import SectionPaper from '../components/common/SectionPaper';
import EmptyState from '../components/common/EmptyState';
import StatCard from '../components/dashboard/StatCard';
import StatusChip from '../components/orders/StatusChip';
import { formatDate, formatMoney } from '../utils/formatters';

function UserDetails({ user }) { if (!user) return <SectionPaper><EmptyState icon={<People fontSize="large" />} title="Выберите пользователя" /></SectionPaper>; return <SectionPaper sx={{ p: { xs: 2, sm: 2.5 } }}><Stack spacing={2.25}><Box><Typography variant="h6">{user.full_name || `Пользователь #${user.id}`}</Typography><Typography variant="body2" color="text.secondary">Создан: {formatDate(user.created_at)}</Typography></Box><Box sx={{ display: 'grid', gap: 1.25, gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' } }}><TextField label="Телефон" size="small" value={user.phone || ''} InputProps={{ readOnly: true }} /><TextField label="Email" size="small" value={user.email || ''} InputProps={{ readOnly: true }} /><TextField label="Адрес доставки" size="small" value={user.delivery_address || ''} InputProps={{ readOnly: true }} sx={{ gridColumn: { sm: '1 / -1' } }} /></Box><Box sx={{ display: 'grid', gap: 2, gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' } }}><StatCard label="Заказы клиента" value={user.orders_count || 0} icon={<ReceiptLong />} /><StatCard label="Сумма заказов" value={formatMoney(user.orders_sum)} icon={<Paid />} color="success.main" /></Box><Divider /><Typography fontWeight={800}>Заказы пользователя</Typography>{(user.orders || []).length ? <Stack spacing={1}>{user.orders.map((order) => <Card variant="outlined" key={order.id}><CardContent sx={{ p: 1.5, '&:last-child': { pb: 1.5 } }}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={800}>Заказ #{order.id}</Typography><Typography variant="caption" color="text.secondary">{formatDate(order.created_at)}</Typography></Box><Box textAlign="right"><StatusChip status={order.status} /><Typography fontWeight={800} sx={{ mt: .5 }}>{formatMoney(order.total_amount)}</Typography></Box></Stack></CardContent></Card>)}</Stack> : <EmptyState title="У пользователя пока нет заказов" sx={{ py: 3 }} />}</Stack></SectionPaper>; }
export default function UsersPage({ users, selectedUser, setSelectedUser, search, setSearch }) { return <Stack spacing={3}><Box><Typography variant="h5">Пользователи</Typography><Typography color="text.secondary">Профили клиентов и история покупок</Typography></Box><Box sx={{ display: 'grid', gap: 2, gridTemplateColumns: { xs: '1fr', lg: '400px minmax(0, 1fr)' }, alignItems: 'start' }}><SectionPaper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2 }}><TextField size="small" fullWidth placeholder="ФИО, телефон, email" value={search} onChange={(event) => setSearch(event.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><Search /></InputAdornment> }} /></Box><Divider />{users.length ? <Stack divider={<Divider />}>{users.map((user) => <Box key={user.id} onClick={() => setSelectedUser(user)} sx={{ p: 1.75, cursor: 'pointer', '&:hover': { bgcolor: 'action.hover' } }}><Typography fontWeight={800}>{user.full_name || `Пользователь #${user.id}`}</Typography><Typography variant="body2" color="text.secondary">{user.phone || user.email || 'Контакты не указаны'}</Typography><Typography variant="caption" color="text.secondary">{user.orders_count} заказов · {formatMoney(user.orders_sum)}</Typography></Box>)}</Stack> : <EmptyState icon={<People fontSize="large" />} title="Пользователи не найдены" />}</SectionPaper><UserDetails user={selectedUser || users[0]} /></Box></Stack>; }
